<?php
    $this->title = "My Users";
    $this->headTitle($this->title);
?>
<p><a href="<?php echo $this->url(array('controller'=>'User',
'action'=>'add'));?>">Add new user</a></p>
<table>
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Email</th>
        <th>Password</th>
        <th>Address</th>        
        <th>Description</th>
        <th>Pets</th>
        <th>Photo</th>
        <th>Gender</th>
        <th>City</th>        
        <th>Rol</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach($this->users as $user) : ?>
    <tr>
        <td><?php echo $this->escape($user->iduser);?></td>
        <td><?php echo $this->escape($user->name);?></td>
        <td><?php echo $this->escape($user->email);?></td>
        <td><?php echo $this->escape($user->password);?></td>
        <td><?php echo $this->escape($user->address);?></td>
        <td><?php echo $this->escape($user->description);?></td>
        <td><?php echo $this->escape($user->pets);?></td>
        <td><?php echo $this->escape($user->photo);?></td>
        <td><?php echo $this->escape($user->genders_idgender);?></td>
        <td><?php echo $this->escape($user->cities_idcity);?></td>
        <td><?php echo $this->escape($user->roles_idrol);?></td>
        <td>
        <a href="<?php echo $this->url(array('controller'=>'User',
        'action'=>'edit', 'id'=>$user->iduser));?>">Edit</a>
        <a href="<?php echo $this->url(array('controller'=>'User',
        'action'=>'delete', 'id'=>$user->iduser));?>">Delete</a>
        </td>
    </tr>
    <?php endforeach; ?>
</table>
